# Generated by Django 3.0.3 on 2020-09-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinson_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='Jitter_absolute',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='Jitter_ddp',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='Jitter_percentage',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='d2',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='mdvp_avq',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='mdvp_ppq',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='mdvp_rap',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='mdvp_shimmer',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='mdvp_shimmer_db',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='nhr',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='ppe',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='result',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='rpde',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='shimmer_apq3',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='shimmer_apq5',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='shimmer_dda',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='spread_2',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinson_app.Topic')),
            ],
        ),
    ]
