# Generated by Django 3.0.3 on 2020-09-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinson_app', '0002_auto_20200903_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Test',
        ),
    ]
