# Generated by Django 3.0.3 on 2020-09-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinson_app', '0003_auto_20200903_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
